### ISSUE TITLE
Add *ngIf clausule to the pagination

### ISSUE THREAD

**Issue by Arley-Fernandez-Taximo** [relair/material-dynamic-table#1]
This is a great library but, in all cases it is not necessary to paginate, I only want to show 5 elements in a table of information thanks.

**Comment by relair** [comment]
I couldn't easily use *ngIf for aginator as it caused some issues with @ViewChild, however I've added the ability to set paginator to null and then there will be no paginator visible. You can now also use a custom paginator, which would make existing one to be hidden.
For versions before 1.1.1 you could just use some css to set paginator to display:none.
