### ISSUE TITLE
TypeScript error on strict build

### ISSUE THREAD

**Issue by stephenscholz** [relair/material-dynamic-table#11]
With a strict tsconfig the build throws 

`ERROR in node_modules/material-dynamic-table/material-dynamic-table.d.ts.ɵb.html(1,1): Type 'undefined' cannot be used as an index type.
node_modules/material-dynamic-table/material-dynamic-table.d.ts.ɵc.html(1,1): Type 'undefined' cannot be used as an index type.`

i guess the following 2 lines causes this issue 
https://github.com/relair/material-dynamic-table/blob/241427c692d37d7a8360b7d7880bd664f981f529/projects/material-dynamic-table/src/lib/table-cell/cell-types/date-cell.component.ts#L7
https://github.com/relair/material-dynamic-table/blob/241427c692d37d7a8360b7d7880bd664f981f529/projects/material-dynamic-table/src/lib/table-cell/cell-types/text-cell.component.ts#L7

**Comment by relair** [comment]
I have enabled some strict properties for the build and updated the code, which should fix this particular issue that you were having. It will make name a required property, although it still may be empty when needed. It should also make the performance a little bit better as it wouldn't need to call prepareColumnName function as often.
