### ISSUE TITLE
Server Side Sorting and Pagination using meterial-dynamic-table

### ISSUE THREAD

**Issue by SanjibKarmakar1** [relair/material-dynamic-table#12]
1. How sorting can be handled at server side and do we need data-source folder itself in that case as it contains mostly logics for client side filtering?
2. Is there any method exposed for pagination? I need to handle the same from server side and need the details like pagesize and pageNo on click event!
3. Does this support multiTemplateDataRow in case child table needs to  be opened on clicking on parent table row.

**Comment by relair** [comment]
This library is built on top of Angular Material, there are plenty of materials available online.
You could start with https://blog.angular-university.io/angular-material-data-table/

For this library data is handled by data source - it is up to you whatever implementation you choose for it - pagination should be handled there as well.

The table doesn't have multiTemplateDataRow enabled, however you can still customise the layout of each cell type by providing a template for it.
