### ISSUE TITLE
Build error with Ivy and Angular 9

### ISSUE THREAD

**Issue by miroo93** [relair/material-dynamic-table#14]
Hi,

I recently upgrade my project to latest angular 9 with Ivy compiler and I'm having an issue building my project.
I'm using:
- typescript 3.7.5
- material-dynamic-table v8.3.0
- [Ivy ON](https://angular.io/guide/ivy#aot-and-ivy)
- [NGCC postinstall script](https://angular.io/guide/ivy#speeding-up-ngcc-compilation)

When running ng build, here are the errors:
```
Compiling material-dynamic-table : es2015 as esm2015

ERROR in Failed to compile entry-point material-dynamic-table (es2015 as esm2015) due to compilation errors:
node_modules/material-dynamic-table/fesm2015/material-dynamic-table.js:262:38 - error NG1010: @ViewChild predicate cannot be interpreted

262     sort: [{ type: ViewChild, args: [MatSort, { static: true },] }],
                                         ~~~~~~~
node_modules/material-dynamic-table/fesm2015/material-dynamic-table.js:540:26 - error NG1010: Value at position 1 in the NgModule.imports of DynamicTableModule is not a reference: [object Object]

540                 imports: [
                             ~
541                     CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
547                     MatTooltipModule
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
548                 ],
    ~~~~~~~~~~~~~~~~~
```

It also fails with same errors on the postinstall script:

package.json
> "postinstall": "ngcc --properties --no-async es2015 browser module main --first-only --create-ivy-entry-points "

I added the _--no-async_ flag as suggested [here](https://github.com/angular/angular/issues/34275) but the problem remains

Any ideas why this is happening?  
Is it compatible and tested with latest release angular 9?

**Comment by relair** [comment]
I made the versioning consistent with angular version it is supporting when I have updated it for Ivy with angular 8 a while back. Looks like they made some more breaking changes in angular 9, so I will probably need to update  the library to make it work again. Hopefully I will find some time soon to take a look at that.

**Comment by relair** [comment]
It looks like it's not an issue with Angular or Ivy (for which the project was updated before), but it's caused by the breaking changes in Angular Material Library (which this library depends on):

> Breaking changes:
Components can no longer be imported through "@angular/material". Use the individual secondary entry-points, such as @angular/material/button.

I will create a new version - 9.3.0, that will work with Angular Material ^9.0.0. I will also add some more information about versioning to the readme.

**Comment by relair** [comment]
Version 9.3.0 should now work with Angular Material ^9.0.0. Example is building fine under the settings you described.
