### ISSUE TITLE
error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by jtalics** [relair/material-dynamic-table#15]
After inserting only this line into app.module.ts:

`import { DynamicTableModule } from 'material-dynamic-table';
`
I am getting a lot of these errors: 

ERROR in ../node_modules/@angular/cdk/bidi/dir.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
    ../node_modules/@angular/cdk/bidi/dir.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/@angular/cdk/table/text-column.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
    ../node_modules/@angular/core/core.d.ts(433,9): error TS1086: An accessor cannot be declared in an ambient context.
    ../node_modules/material-dynamic-table/lib/dynamic-table.component.d.ts(2,50): error TS2306: File '/home/user0/vscode-projects/node_modules/@angular/material/index.d.ts' is not a module.

HTH.  Thank you for donating this excellent module!

**Comment by relair** [comment]
Its probably related to issue #9, try version 9.3.0 if you are using Angular Material 9
