### ISSUE TITLE
Can't bind to 'colums' and 'dataSource'

### ISSUE THREAD

**Issue by danielcai1987** [relair/material-dynamic-table#2]
Dear relair,

Thank you for making this useful component.
When I tried it on Angular 7.1.3. I got the following error.

Uncaught Error: Template parse errors:
Can't bind to 'columns' since it isn't a known property of 'mdt-dynamic-table'.
1. If 'mdt-dynamic-table' is an Angular component and it has 'columns' input, then verify that it is part of this module.

Can't bind to 'dataSource' since it isn't a known property of 'mdt-dynamic-table'.
1. If 'mdt-dynamic-table' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'mdt-dynamic-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by relair** [comment]
Have you imported the module? See step 3 of the getting started guide. It looks like the component wasn't registered, which means that something is probably wrong with the module imports.
