### ISSUE TITLE
Predefine filter

### ISSUE THREAD

**Issue by pnguyen535** [relair/material-dynamic-table#4]
Is there away I set the initial filter?

Thanks

**Comment by relair** [comment]
Not at the moment unfortunately. It would be good to add a method that can set up filter per column, so there will be some validation, I'll try to add something in the future.

**Comment by relair** [comment]
I have released a new version 1.2.0 that has a method setFilter(columnName: string, filter: any) that allows to set a filter for a column with provided name. 
I couldn't add validation for model type at this time, so make sure you use the right filter model for the column type.
