### ISSUE TITLE
paginator  isn't a known property of 'mdt-dynamic-table'

### ISSUE THREAD

**Issue by SuperPanBagna** [relair/material-dynamic-table#5]
I have implemented material-dynamic-table in a "table-material" component  to reuse it at different places in my project.
I am able to display a table with pagination (default + custom pagination with internal paginator). 

However when I reload my datas in my current page I loose the pagination. 

So I've tried to input the "paginator" property to , in a first time, set an external paginator (with  MatPaginator) , then to hide the internal paginator passing null. 

Both cases failed with the same error  : 
 
![image](https://user-images.githubusercontent.com/36860565/57481447-268a1d00-7270-11e9-8d33-72ee437d3326.png)

table-material.component.html ( Trying to hide )

`    <mdt-dynamic-table [columns]="columns" [dataSource]="dataSource"  [paginator]="nullVariable"></mdt-dynamic-table>
`
with ` public nullVariable = null` in table-material.component.ts

It just looks that 'paginator' input doesn't work.

(Angular 7.1.2;
material-dynamic-table v1.1.2) 

Thanks for this project very very useful.

**Comment by relair** [comment]
I have double checked with stackblitz and it does work as expected, maybe you didn't do npm install and it still is using the old version even though package.json have new version referenced?
Also as a hint you can just have  [paginator]="null", no need for nullVariable.
