### ISSUE TITLE
How do you update the data in the dataSource without reloading?

### ISSUE THREAD

**Issue by bostondevin** [relair/material-dynamic-table#8]
I tried this and it didn't error, but didn't do anything - i'm trying to delete rows

    this.dataSource= new MatTableDataSource<any>(that.newResults)

**Comment by relair** [comment]
You can't replace data source after material data table has been initialized as it subscribes to the table at the start.
Please refer to MatTableDataSource  documentation https://material.angular.io/components/table/api#MatTableDataSource for details about how to use this data source.
In short I can tell you that you can update your data by setting this.dataSource.data like
this.dataSource.data = newDataArray
Keep in mind that although you can update this.dataSource.data directly, to trigger an update you need to set the data property or update a filter or sort.
